# -*- coding: utf-8 -*-
"""Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19sEyc1B1fYirCCPgBVCs--MmlB3ML7nc

https://www.policia.gov.co/delitos-de-impacto/homicidios

https://www.policia.gov.co/contenido/homicidios-2017

Objetivo: La idea por la que se decidió analizar los datos de homicidios intencionales a nivel nacional (Colombia) era entender la realidad social y política del país. El rango de estudio (2015-2025) abarca tres periodos presidenciales distintos y la implementación de diversas estrategias de seguridad. Los datos permiten evaluar, de manera objetiva y sin sesgos ideológicos, qué políticas han tenido un efecto real en la preservación de la vida.

Identificación de patrones y tendencias: Colombia ha vivido cambios significativos en su dinámica de seguridad tras el Acuerdo de Paz de 2016 y acuerdos de Paz Total.

Comprensión de Factores de Riesgo: Cruzar los datos de homicidios podrá a ayudar a  entender qué factores están impulsando la violencia en regiones específicas.

- Total de homicidios en Colombia entre el 2015 y el 2025
- Cual es el departamento con más homicidios
- En que fechas se presentan la mayor cantidad de homicidios
- Cual es el arma más común para efectuar estos homicidios
- Cual es la población más afectada, Hombres, Mujeres o adolecentes y niños.
- Como le fue a Antioquia (Por municio)
- Cual es la población más afectada en Antioquia, Adultos, adolecentes o niños.
"""

import pandas as pd
import matplotlib.pyplot as plt
import datetime as datet

# Nota: Usar 'r' antes de la ruta para manejar barras invertidas (\)
path2015 = '/content/drive/MyDrive/Colab Notebooks/HomicidioIntencional2015.xlsx'
path2016 = '/content/drive/MyDrive/Colab Notebooks/HomicidioIntencional2016.xlsx'
path2017 = '/content/drive/MyDrive/Colab Notebooks/HomicidioIntencional2017.xlsx'
path2018 = '/content/drive/MyDrive/Colab Notebooks/HomicidioIntencional2018.xlsx'
path2019 = '/content/drive/MyDrive/Colab Notebooks/HomicidioIntencional2019.xlsx'
path2020 = '/content/drive/MyDrive/Colab Notebooks/HomicidioIntencional2020.xlsx'
path2021 = '/content/drive/MyDrive/Colab Notebooks/HomicidioIntencional2021.xlsx'
path2022 = '/content/drive/MyDrive/Colab Notebooks/HomicidioIntencional2022.xlsx'
path2023 = '/content/drive/MyDrive/Colab Notebooks/HomicidioIntencional2023.xlsx'
path2024 = '/content/drive/MyDrive/Colab Notebooks/HomicidioIntencional2024.xlsx'
path2025 = '/content/drive/MyDrive/Colab Notebooks/HomicidioIntencional2025.xlsx'
df2015 = pd.read_excel(path2015)
df2016 = pd.read_excel(path2016)
df2017 = pd.read_excel(path2017)
df2018 = pd.read_excel(path2018)
df2019 = pd.read_excel(path2019)
df2020 = pd.read_excel(path2020)
df2021 = pd.read_excel(path2021)
df2022 = pd.read_excel(path2022)
df2023 = pd.read_excel(path2023)
df2023.rename(columns={'ARMA MEDIO':'ARMAS MEDIOS'}, inplace=True)
df2024 = pd.read_excel(path2024)
df2025 = pd.read_excel(path2025)

df2021.head()

# Mostrar las primeras 5 filas
#df2015.head()
#df2023.info()
#df2025.info()

# Mostrar los Medios ALMOHADA
#df[(df["ARMAS MEDIOS"] == 'ARMA DE FUEGO')]
#df[(df["FECHA HECHO"] == 20170314)]

#con Shape me cuenta la cantidad de filas. dataframe[["columna"].shape
fechasanos = ["2015","2016","2017","2018","2019","2020","2021","2022","2023","2024","2025"]
totalhomicidios = [df2015['CANTIDAD'].sum(), df2016['CANTIDAD'].sum(), df2017['CANTIDAD'].sum(), df2018['CANTIDAD'].sum(), df2019['CANTIDAD'].sum(), df2020['CANTIDAD'].sum(), df2021['CANTIDAD'].sum(), df2022['CANTIDAD'].sum(), df2023['CANTIDAD'].sum(), df2024['CANTIDAD'].sum(), df2025['CANTIDAD'].sum()]
#print(totalhomicidios)
#print(df2017['CANTIDAD'].count())
#df2018.describe()
#df2019.describe()
#df2020.describe()
#df2021.describe()
#df2022.describe()
#df2023.describe()
#df2024.describe()
#df2025.describe()
# Equivalente al Like
#medios = df['ARMAS MEDIOS'].str.contains('FUEGO')
#print(medios)
#df[(df["ARMAS MEDIOS"] == medios)]

#Grafico:
#Grafico
#plt.figure(figsize=(15,5)) #Definimos el tamaño de la figura

#plt.plot(fechasanos, totalhomicidios, marker = '*', linestyle = 'dotted', label="Homicidios x Años", color='red')

# Crear el gráfico
fig, ax = plt.subplots(figsize=(15, 8))
#fig, ax = plt.plot(fechasanos, totalhomicidios, marker = '*', linestyle = 'dotted', label="Homicidios x Años", color='red')

ax.plot(fechasanos, totalhomicidios, marker = '*', linestyle = 'dotted', label="Homicidios x Años", color='red')

# El bucle for usando tus listas
for x, y in zip(fechasanos, totalhomicidios):
    ax.annotate(f'{y}',
                xy=(x, y),
                xytext=(0, 10),
                textcoords='offset points',
                ha='center',
                fontsize=10)

# Labels and title
plt.xlabel('Año')
plt.ylabel('TotalHomicidios')
plt.title('Homicidios Nacionales (Colombia)')
plt.legend()
plt.show()

## Homiciodios en Antioquia

antioquia2015 = df2015["DEPARTAMENTO"] == 'ANTIOQUIA'
datosantioquia2015 = df2015[antioquia2015]

antioquia2016 = df2016["DEPARTAMENTO"] == 'ANTIOQUIA'
datosantioquia2016 = df2016[antioquia2016]

antioquia2017 = df2017["DEPARTAMENTO"] == 'ANTIOQUIA'
datosantioquia2017 = df2017[antioquia2017]

antioquia2018 = df2018["DEPARTAMENTO"] == 'ANTIOQUIA'
datosantioquia2018 = df2018[antioquia2018]

antioquia2019 = df2019["DEPARTAMENTO"] == 'ANTIOQUIA'
datosantioquia2019 = df2019[antioquia2019]

antioquia2020 = df2020["DEPARTAMENTO"] == 'ANTIOQUIA'
datosantioquia2020 = df2020[antioquia2020]

antioquia2021 = df2021["DEPARTAMENTO"] == 'ANTIOQUIA'
datosantioquia2021 = df2021[antioquia2021]

antioquia2022 = df2022["DEPARTAMENTO"] == 'ANTIOQUIA'
datosantioquia2022 = df2022[antioquia2022]

antioquia2023 = df2023["DEPARTAMENTO"] == 'ANTIOQUIA'
datosantioquia2023 = df2023[antioquia2023]

antioquia2024 = df2024["DEPARTAMENTO"] == 'ANTIOQUIA'
datosantioquia2024 = df2024[antioquia2024]

antioquia2025 = df2025["DEPARTAMENTO"] == 'ANTIOQUIA'
datosantioquia2025 = df2025[antioquia2025]

#display(datosantioquia2015)
#df[(df["FECHA HECHO"] == 20170314)]


fechasanosantioquia = ["2015","2016","2017","2018","2019","2020","2021","2022","2023","2024","2025"]
totalhomicidios = [datosantioquia2015['CANTIDAD'].sum(), datosantioquia2016['CANTIDAD'].sum(), datosantioquia2017['CANTIDAD'].sum(), datosantioquia2018['CANTIDAD'].sum(), datosantioquia2019['CANTIDAD'].sum(), datosantioquia2020['CANTIDAD'].sum(), datosantioquia2021['CANTIDAD'].sum(), datosantioquia2022['CANTIDAD'].sum(), datosantioquia2023['CANTIDAD'].sum(), datosantioquia2024['CANTIDAD'].sum(), datosantioquia2025['CANTIDAD'].sum()]

#Grafico:
plt.figure(figsize=(15,5)) #Definimos el tamaño de la figura
plt.plot(fechasanos, totalhomicidios, marker = 'o', linestyle = '-', label="Homicidios x Años", color='green')

# Labels and title
plt.xlabel('Año')
plt.ylabel('TotalHomicidios')
plt.title('Homicidios en el Departamento (Antioquia)')
plt.legend()
plt.show()

# Feminicidios

import numpy as np

feminicidios2015 = df2015["GENERO"] == 'FEMENINO'
datosfeminicidios2015 = df2015[feminicidios2015]

feminicidios2016 = df2016["GENERO"] == 'FEMENINO'
datosfeminicidios2016 = df2016[feminicidios2016]

feminicidios2017 = df2017["GENERO"] == 'FEMENINO'
datosfeminicidios2017 = df2017[feminicidios2017]

feminicidios2018 = df2018["GENERO"] == 'FEMENINO'
datosfeminicidios2018 = df2018[feminicidios2018]

feminicidios2019 = df2019["GENERO"] == 'FEMENINO'
datosfeminicidios2019 = df2019[feminicidios2019]

feminicidios2020 = df2020["GENERO"] == 'FEMENINO'
datosfeminicidios2020 = df2020[feminicidios2020]

feminicidios2021 = df2021["GENERO"] == 'FEMENINO'
datosfeminicidios2021 = df2021[feminicidios2021]

feminicidios2022 = df2022["GENERO"] == 'FEMENINO'
datosfeminicidios2022 = df2022[feminicidios2022]

feminicidios2023 = df2023["GENERO"] == 'FEMENINO'
datosfeminicidios2023 = df2023[feminicidios2023]

feminicidios2024 = df2024["GENERO"] == 'FEMENINO'
datosfeminicidios2024 = df2024[feminicidios2024]

feminicidios2025 = df2025["GENERO"] == 'FEMENINO'
datosfeminicidios2025 = df2025[feminicidios2025]

#Comparación Hombres

homicidioshombres2015 = df2015["GENERO"] == 'MASCULINO'
datoshomicidioshombres2015 = df2015[homicidioshombres2015]

homicidioshombres2016 = df2016["GENERO"] == 'MASCULINO'
datoshomicidioshombres2016 = df2016[homicidioshombres2016]

homicidioshombres2017 = df2017["GENERO"] == 'MASCULINO'
datoshomicidioshombres2017 = df2017[homicidioshombres2017]

homicidioshombres2018 = df2018["GENERO"] == 'MASCULINO'
datoshomicidioshombres2018 = df2018[homicidioshombres2018]

homicidioshombres2019 = df2019["GENERO"] == 'MASCULINO'
datoshomicidioshombres2019 = df2019[homicidioshombres2019]

homicidioshombres2020 = df2020["GENERO"] == 'MASCULINO'
datoshomicidioshombres2020 = df2020[homicidioshombres2020]

homicidioshombres2021 = df2021["GENERO"] == 'MASCULINO'
datoshomicidioshombres2021 = df2021[homicidioshombres2021]

homicidioshombres2022 = df2022["GENERO"] == 'MASCULINO'
datoshomicidioshombres2022 = df2022[homicidioshombres2022]

homicidioshombres2023 = df2023["GENERO"] == 'MASCULINO'
datoshomicidioshombres2023 = df2023[homicidioshombres2023]

homicidioshombres2024 = df2024["GENERO"] == 'MASCULINO'
datoshomicidioshombres2024 = df2024[homicidioshombres2024]

homicidioshombres2025 = df2025["GENERO"] == 'MASCULINO'
datoshomicidioshombres2025 = df2025[homicidioshombres2025]

#Comparación Niños y Adolecentes

homicidiosninosadolecentes2015 = df2015["AGRUPA EDAD PERSONA"].isin(["ADOLESCENTES","MENORES"])
datoshomicidiosninosadolecentes2015 = df2015[homicidiosninosadolecentes2015]

homicidiosninosadolecentes2016 = df2016["AGRUPA EDAD PERSONA"].isin(["ADOLESCENTES","MENORES"])
datoshomicidiosninosadolecentes2016 = df2016[homicidiosninosadolecentes2016]

homicidiosninosadolecentes2017 = df2017["AGRUPA EDAD PERSONA"].isin(["ADOLESCENTES","MENORES"])
datoshomicidiosninosadolecentes2017 = df2017[homicidiosninosadolecentes2017]

homicidiosninosadolecentes2018 = df2018["AGRUPA EDAD PERSONA"].isin(["ADOLESCENTES","MENORES"])
datoshomicidiosninosadolecentes2018 = df2018[homicidiosninosadolecentes2018]

homicidiosninosadolecentes2019 = df2019["AGRUPA EDAD PERSONA"].isin(["ADOLESCENTES","MENORES"])
datoshomicidiosninosadolecentes2019 = df2019[homicidiosninosadolecentes2019]

homicidiosninosadolecentes2020 = df2020["AGRUPA EDAD PERSONA"].isin(["ADOLESCENTES","MENORES"])
datoshomicidiosninosadolecentes2020 = df2020[homicidiosninosadolecentes2020]

homicidiosninosadolecentes2021 = df2021["AGRUPA EDAD PERSONA"].isin(["ADOLESCENTES","MENORES"])
datoshomicidiosninosadolecentes2021 = df2021[homicidiosninosadolecentes2021]

homicidiosninosadolecentes2022 = df2022["AGRUPA EDAD PERSONA"].isin(["ADOLESCENTES","MENORES"])
datoshomicidiosninosadolecentes2022 = df2022[homicidiosninosadolecentes2022]

homicidiosninosadolecentes2023 = df2023["AGRUPA EDAD PERSONA"].isin(["ADOLESCENTES","MENORES"])
datoshomicidiosninosadolecentes2023 = df2023[homicidiosninosadolecentes2023]

homicidiosninosadolecentes2024 = df2024["AGRUPA EDAD PERSONA"].isin(["ADOLESCENTES","MENORES"])
datoshomicidiosninosadolecentes2024 = df2024[homicidiosninosadolecentes2024]

homicidiosninosadolecentes2025 = df2025["AGRUPA EDAD PERSONA"].isin(["ADOLESCENTES","MENORES"])
datoshomicidiosninosadolecentes2025 = df2025[homicidiosninosadolecentes2025]

#display(datoshomicidiosninosadolecentes2022)
#df[(df["FECHA HECHO"] == 20170314)]


fechasanosfeminicidios = ["2015","2016","2017","2018","2019","2020","2021","2022","2023","2024","2025"]
totalhomicidiosfeminicidios = np.array([datosfeminicidios2015['CANTIDAD'].sum(), datosfeminicidios2016['CANTIDAD'].sum(), datosfeminicidios2017['CANTIDAD'].sum(), datosfeminicidios2018['CANTIDAD'].sum(), datosfeminicidios2019['CANTIDAD'].sum(), datosfeminicidios2020['CANTIDAD'].sum(), datosfeminicidios2021['CANTIDAD'].sum(), datosfeminicidios2022['CANTIDAD'].sum(), datosfeminicidios2023['CANTIDAD'].sum(), datosfeminicidios2024['CANTIDAD'].sum(), datosfeminicidios2025['CANTIDAD'].sum()])

totalhomicidioshombres = np.array([datoshomicidioshombres2015['CANTIDAD'].sum(), datoshomicidioshombres2016['CANTIDAD'].sum(), datoshomicidioshombres2017['CANTIDAD'].sum(), datoshomicidioshombres2018['CANTIDAD'].sum(), datoshomicidioshombres2019['CANTIDAD'].sum(), datoshomicidioshombres2020['CANTIDAD'].sum(), datoshomicidioshombres2021['CANTIDAD'].sum(), datoshomicidioshombres2022['CANTIDAD'].sum(), datoshomicidioshombres2023['CANTIDAD'].sum(), datoshomicidioshombres2024['CANTIDAD'].sum(), datoshomicidioshombres2025['CANTIDAD'].sum()])

totalhomicidiosninosadolecentes = np.array([datoshomicidiosninosadolecentes2015['CANTIDAD'].sum(), datoshomicidiosninosadolecentes2016['CANTIDAD'].sum(), datoshomicidiosninosadolecentes2017['CANTIDAD'].sum(), datoshomicidiosninosadolecentes2018['CANTIDAD'].sum(), datoshomicidiosninosadolecentes2019['CANTIDAD'].sum(), datoshomicidiosninosadolecentes2020['CANTIDAD'].sum(), datoshomicidiosninosadolecentes2021['CANTIDAD'].sum(), datoshomicidiosninosadolecentes2022['CANTIDAD'].sum(), datoshomicidiosninosadolecentes2023['CANTIDAD'].sum(), datoshomicidiosninosadolecentes2024['CANTIDAD'].sum(), datoshomicidiosninosadolecentes2025['CANTIDAD'].sum()])

#Grafico:
plt.figure(figsize=(15,8)) #Definimos el tamaño de la figura
plt.plot(fechasanosfeminicidios, totalhomicidiosfeminicidios, marker = '*', linestyle = 'dotted', label="Homicidios Mujeres", color='deeppink')
plt.plot(fechasanosfeminicidios, totalhomicidioshombres, marker = 'o', linestyle = 'dashed', label="Homicidios Hombres", color='royalblue')
plt.plot(fechasanosfeminicidios, totalhomicidiosninosadolecentes, marker = 's', linestyle = 'dashdot', label="Homicidios Menores Edad", color='peru')

# Labels and title
plt.xlabel('Año')
plt.ylabel('TotalHomicidios')
plt.title('Homicidios Intencionales en Hombre vs Mujeres vs Menores')
plt.legend()
plt.show()

#Comparación Mujeres vs Niños y Adolecentes:

#Grafico:
plt.figure(figsize=(15,8)) #Definimos el tamaño de la figura
plt.plot(fechasanosfeminicidios, totalhomicidiosfeminicidios, marker = '*', linestyle = 'dotted', label="Homicidios Mujeres", color='deeppink')
#plt.plot(fechasanosfeminicidios, totalhomicidioshombres, marker = 'o', linestyle = 'dotted', label="Homicidios Hombres", color='royalblue')
plt.plot(fechasanosfeminicidios, totalhomicidiosninosadolecentes, marker = 's', linestyle = 'dashdot', label="Homicidios Menores Edad", color='peru')

# Labels and title
plt.xlabel('Año')
plt.ylabel('TotalHomicidios')
plt.title('Feminicidios vs H. Menores Intencionales')
plt.legend()
plt.show()

#Comparación de comportamiento

#Grafico:
#plt.figure(figsize=(15,8)) #Definimos el tamaño de la figura
#plt.plot(fechasanosfeminicidios, totalhomicidiosfeminicidios/totalhomicidiosfeminicidios.max(), marker = '*', linestyle = 'dotted', label="Homicidios Mujeres", color='deeppink')
#plt.plot(fechasanosfeminicidios, totalhomicidioshombres/totalhomicidioshombres.max(), marker = 'o', linestyle = 'dashed', label="Homicidios Hombres", color='royalblue')
#plt.plot(fechasanosfeminicidios, totalhomicidiosninosadolecentes/totalhomicidiosninosadolecentes.max(), marker = 's', linestyle = 'dashdot', label="Homicidios Menores Edad", color='peru')

f, axs = plt.subplots(nrows = 3, ncols = 1, figsize = (15, 8))
axs[0].plot(fechasanosfeminicidios, totalhomicidiosfeminicidios)
axs[0].set_ylabel("Homicidios Mujeres")
axs[0].set_title("")

axs[1].plot(fechasanosfeminicidios, totalhomicidioshombres)
axs[1].set_ylabel("Homicidios Hombres")
axs[1].set_title("")

axs[2].plot(fechasanosfeminicidios, totalhomicidiosninosadolecentes)
axs[2].set_ylabel("Homicidios Menores")
axs[2].set_title("")

# Labels and title
#plt.xlabel('Año')
#plt.ylabel('Homicidios')
#plt.title('Comportamiento Homicidios Intencionales')
plt.legend()
plt.show()

#Concatenar todos los DataFrame
#Antes de concatenar
# 1. Organizar la Fecha Hecho, para que todos los DF queden en formato datetime
# 2. Hay un Año que tiene mal la columna "ARMAS MEDIOS"
print("2015")
df2015.info()
print("2016")
df2016.info()
print("2017")
df2017.info()
print("2018")
df2018.info()
print("2019")
df2019.info()
print("2020")
df2020.info()
print("2021")
df2021.info()
print("2022")
df2022.info()
print("2023")
df2023.info()
print("2024")
df2024.info()
print("2025")
df2025.info()
dfconsolidado = pd.concat([df2015, df2016, df2017, df2018, df2019, df2020, df2021, df2022, df2023, df2024, df2025], ignore_index=True)
display(dfconsolidado)